# Generated by Django 3.2.8 on 2021-10-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gemotest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_number', models.IntegerField(default=53425687)),
                ('first_name', models.CharField(max_length=30)),
                ('qr_code', models.ImageField(blank=True, upload_to='')),
                ('last_name', models.CharField(max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('number_of_phone', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('number_of_passport', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('date_of_give_bio', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
            ],
        ),
    ]
