# Generated by Django 3.2.8 on 2021-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gemotest_generate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemotest',
            name='generate_number',
            field=models.IntegerField(default=34404231),
        ),
        migrations.AlterField(
            model_name='gemotest',
            name='number_of_passport',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
