# Generated by Django 3.2.8 on 2021-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211008_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemotest',
            name='generate_number',
            field=models.IntegerField(default=45995229),
        ),
    ]
